services:
  php:
    build:
      context: ./
      dockerfile: ./deploy/local/php.Dockerfile
    restart: unless-stopped
    command: sh -c "composer i && apache2-foreground"
    volumes:
      - .:/var/www/html
    network_mode: host

  queue:
    depends_on:
      - php
    build:
      context: ./
      dockerfile: ./deploy/local/php.Dockerfile
    restart: unless-stopped
    command: sh -c "php artisan queue:listen"
    volumes:
      - .:/var/www/html
    network_mode: host

  db:
    image: mariadb:11.3.2
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped
    network_mode: host

volumes:
  db:
